server:
  port: "8080"

providers:
  # 渠道 1: 钉钉应用私信
  dingtalk_robot:
    app_key: "dingeh9wax4r0ch41juc"
    app_secret: "G3KZoDokYVGP79WgEn4_Hz1OT2vLHa4wcbrjTWxLz1k9mL06uTy3sjbuTCAtmluP"

  # 渠道 2: 钉钉群 Webhook
  dingtalk_webhook:
    webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=bb2aaef5b255e0c84e1cbe4f62acc7767e4277cfc44b9de8ea882e17b925b584"
    secret: "SECbf780ff2b7a0f8263b3842c952acd7b9eff35b6e3aa4a55531aa8911f3a2ecad" # 选填：加签密钥

  # 渠道 3: 邮件服务 (SMTP)
  email:
    smtp_host: "smtp.qq.com"
    smtp_port: 465
    smtp_user: "alert@yourcompany.com"
    smtp_pass: "your_smtp_password_or_token"
    from: "运维告警中心 <alert@yourcompany.com>"